splash = false
ipc = true

wallpaper {
    monitor = HDMI-A-1
    path = /home/calirko/.config/hypr/wallpapers/26-04-16 08-33-33 3443.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/calirko/.config/hypr/wallpapers/26-04-16 08-33-33 3443.jpg
    fit_mode = cover
}

