preload = /home/calirko/.config/hypr/wallpapers/HFdMObmbYAAlB2n_upscayl_4x_upscayl-standard-4x.png
wallpaper = ,/home/calirko/.config/hypr/wallpapers/HFdMObmbYAAlB2n_upscayl_4x_upscayl-standard-4x.png
splash = false
