general {
    lock_cmd = pidof hyprlock >/dev/null || hyprlock
    before_sleep_cmd = pidof hyprlock >/dev/null || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300        # 5 min: turn off screens
    on-timeout = hyprctl dispatch dpms off
on-resume = hyprctl dispatch dp´ms on
}

listener {
    timeout = 360        # 6 min: lock
    on-timeout = pidof hyprlock >/dev/null || hyprlock
}

listener {
    timeout = 600        # 10 min: suspend
    on-timeout = systemctl suspend
}
