preload = /home/calirko/.config/hypr/wallpapers/wallpaper-2.png

wallpaper {
    monitor = HDMI-A-1
    path = /home/calirko/.config/hypr/wallpapers/wallpaper-2.png
    fit_mode = cover
}

ipc = on
splash = false
