# Monitors
# monitorv2 {
#     output   = desc:BOE 0x0A2A
#     mode     = 1920x1200@60
#     position = auto
#     scale    = 1
# }

monitorv2 {
    output   = desc:Samsung Electric Company LF24T35 HX5X803123
    mode     = 1920x1080@75
    position = 0x0
    scale    = 1
}

monitorv2 {
    output    = desc:Samsung Electric Company LF24T35 HX5X802342
    mode      = 1920x1080@75
    position  = 1920x-180
    scale     = 1
    transform = 3
}

# Workspaces
workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:HDMI-A-1, default:true
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1


# Input
input {
    touchpad {
        natural_scroll = false
        tap-to-click   = true
    }
}

gesture = 3, horizontal, workspace

# Autostart
exec-once = /home/calirko/.config/hypr/scripts/laptop-lid-init.sh

# Keybinds
bindl  = , switch:Lid Switch,       exec, /home/calirko/.config/hypr/scripts/laptop-lid-init.sh
bindel = , XF86KbdBrightnessUp,     exec, ~/.config/hypr/scripts/kbd-backlight-notify.sh up
bindel = , XF86KbdBrightnessDown,   exec, ~/.config/hypr/scripts/kbd-backlight-notify.sh down

# Shared config
source = ~/.config/hypr/hyprland.conf
