# Monitors
monitorv2 {
    output   = desc:AOC 22B1WG5 AUWMAXA004846
    mode     = 1920x1080@75
    position = 0x0
    scale    = 1
}

# Workspaces
workspace = 1,  monitor:HDMI-A-1,     default:true
workspace = 2,  monitor:HDMI-A-1
workspace = 3,  monitor:HDMI-A-1
workspace = 4,  monitor:HDMI-A-1
workspace = 5,  monitor:HDMI-A-1
workspace = 6,  monitor:HDMI-A-1
workspace = 7,  monitor:HDMI-A-1
workspace = 8,  monitor:HDMI-A-1
workspace = 9,  monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

# Input
input {
    numlock_by_default = true
}

# Shared config
source = ~/.config/hypr/hyprland.conf
