general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 6
}

# Time
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(235, 235, 235, 1.0)
    font_size = 72
    font_family = Geist Medium
    position = 0, 110
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgba(138, 138, 138, 1.0)
    font_size = 18
    font_family = Geist
    position = 0, 40
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 48
    position = 0, -64
    halign = center
    valign = center

    rounding = 4
    dots_rounding = -1
    outline_thickness = 1
    inner_color = rgb(13, 13, 13)
    outer_color = rgba(255, 255, 255, 0.10)
    check_color = rgba(138, 138, 138, 1.0)
    fail_color = rgba(245, 245, 245, 1.0)
    font_color = rgba(214, 214, 214, 1.0)
    placeholder_text = <span foreground="##6b6b6b">password</span>
    fade_on_empty = false
    dots_size = 0.25
    dots_spacing = 0.3
}

animations {
    animation = fadeIn, 2, 2, snappy
    animation = fadeOut, 2, 2, snappy
}
