preload = /home/calirko/.config/hypr/wallpapers/trees_under_cloudy_sky_grunge_hd_grunge.jpg
wallpaper = ,/home/calirko/.config/hypr/wallpapers/trees_under_cloudy_sky_grunge_hd_grunge.jpg
splash = false
