general {
    lock_cmd = pidof hyprlock >/dev/null || hyprlock
    before_sleep_cmd = pidof hyprlock >/dev/null || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 180       # 3 min: dim to 5%
    on-timeout = [ "$(cat /sys/class/power_supply/AC*/online)" = "0" ] && brightnessctl -s set 5%
    on-resume = brightnessctl -r
}

listener {
    timeout = 600       # 10 min: suspend only on battery
    on-timeout = [ "$(cat /sys/class/power_supply/AC*/online)" = "0" ] && systemctl suspend
}
