wallpaper {
    monitor = HDMI-A-1
    path = /home/calirko/.cache/hypr-wallpaper-crop/HDMI-A-1.png
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = /home/calirko/.cache/hypr-wallpaper-crop/DP-1.png
    fit_mode = cover
}
splash = false
